SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'A%'

select * from  CUSTOMERS
where CUSTOMERNAME LIKE 'A%' OR GENDER  LIKE 'E'

select * from CUSTOMERS  
where YEAR(BIRTHDATE) BETWEEN 1991 AND  1995  OR  GENDER LIKE 'E'

SELECT CUSTOMERNAME,GENDER,CITYID  FROM CUSTOMERS S 
INNER JOIN CITIES C ON C.ID=S.CITYID WHERE CITYID>16 OR GENDER LIKE 'E'



SELECT * FROM CUSTOMERS
SELECT COUNT(ID) AS MÜÞTERÝSAYISI  FROM CUSTOMERS

SELECT * FROM CUSTOMERS


SELECT CITYID+200 AS ZAMLI ,DISTRICTID+3000 AS ZAMLI2 ,boþkolon+100 ZAMNLI3,A.CITY AS ÞEHÝRLER   FROM CUSTOMERS C
INNER JOIN CITIES A ON A.ID=C.CITYID 


SELECT DISTINCT * FROM CUSTOMERS
SELECT * FROM CUSTOMERS

SELECT DISTINCT AGEGROUP FROM CUSTOMERS
SELECT CUSTOMERNAME,AGEGROUP FROM CUSTOMERS
SELECT DISTINCT AGEGROUP,CUSTOMERNAME FROM CUSTOMERS WHERE AGEGROUP='20-35 YAÞ'
SELECT DISTINCT A.CITY FROM CUSTOMERS C
INNER JOIN CITIES A ON A.ID=C.CITYID WHERE CITYID BETWEEN 20 AND 60

SELECT DISTINCT CUSTOMERNAME FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'Sev%'


SELECT DISTINCT CITYID,CITY FROM CUSTOMERS C 
INNER JOIN CITIES A ON A.ID=C.CITYID  ORDER BY CITYID DESC

SELECT DISTINCT CITYID,CITY FROM CUSTOMERS C 
INNER JOIN CITIES A ON A.ID=C.CITYID  ORDER BY CITYID 

SELECT  C.DISTRICTID,A.ID FROM CUSTOMERS C 
INNER JOIN CITIES A ON A.ID=C.CITYID  ORDER BY A.ID DESC ,C.DISTRICTID ASC



SELECT CUSTOMERNAME,UPPER(CUSTOMERNAME) AS BÜYÜK FROM CUSTOMERS 

SELECT CUSTOMERNAME FROM CUSTOMERS WHERE UPPER(CUSTOMERNAME)='SEVDA AKÇAN'
SELECT CONCAT(CUSTOMERNAME,TCNUMBER) AS BÝRLEÞTÝRME FROM CUSTOMERS
SELECT CUSTOMERNAME  + ' ' + GENDER + ' ' + TCNUMBER FROM CUSTOMERS-- BOÞLUKLU 
SELECT CUSTOMERNAME + ' ' + GENDER FROM CUSTOMERS


SELECT LEN(TCNUMBER) FROM CUSTOMERS
SELECT CUSTOMERNAME,LEN(TCNUMBER) FROM CUSTOMERS WHERE LEN(TCNUMBER)<11

SELECT CUSTOMERNAME,
       LEN(TCNUMBER) AS TC,CASE
	   WHEN LEN(TCNUMBER)=11 THEN 'DOÐRU'
	   ELSE SUBSTRING(CUSTOMERNAME,1,9)
	   END AS TCDURUMU
	   FROM CUSTOMERS,


SELECT CUSTOMERNAME,
       LEN(TCNUMBER) AS TC,CASE
	   WHEN LEN(TCNUMBER)=11 THEN 'DOÐRU'
	   ELSE 'YANLIÞ'
	   END AS TCDURUMU
	   FROM CUSTOMERS


SELECT SUBSTRING(CUSTOMERNAME,1,9) FROM CUSTOMERS

SELECT CHARINDEX(CUSTOMERNAME,'A') FROM CUSTOMERS
SELECT CHARINDEX('A',CUSTOMERNAME)  FROM CUSTOMERS--- ANIN ÝSÝMDE KELÝMEDE KAÇINCI HARF OLDUÐUNU SÖYLER
SELECT RIGHT(CUSTOMERNAME,5) FROM CUSTOMERS
SELECT LEFT(CUSTOMERNAME,5) FROM CUSTOMERS
SELECT REPLACE(CUSTOMERNAME,'A','W') FROM CUSTOMERS---- AANIN YERÝNE W YAZAR KELÝMEDE
SELECT FORMAT(BIRTHDATE,'2024-12-04') FROM CUSTOMERS
SELECT CAST(123 AS VARCHAR) AS KARAKTER
SELECT TRY_CAST('abc' AS INT) AS SayisalDeger;  -- NULL döner, hata vermez.
SELECT TRY_CONVERT(INT, '123.45') AS SayisalDeger; -- NULL döner, hata vermez.
-- CAST Kullanýmý
SELECT CAST(123 AS VARCHAR) AS KarakterDeger;----------SAYISAL BÝR ÝFADEYÝ KARAKTERE DÖNÜÞTÜRME
-- CONVERT Kullanýmý
SELECT CONVERT(VARCHAR, 123) AS KarakterDeger;


SELECT CAST(CUSTOMERNAME AS VARCHAR) AS KARAKETR FROM CUSTOMERS
SELECT CAST(TCNUMBER AS FLOAT ) AS  SAYISAL FROM CUSTOMERS
SELECT CAST(BIRTHDATE AS DATE ) AS TARÝHÝDÐER FROM CUSTOMERS


SELECT CONVERT(VARCHAR,BIRTHDATE,101) AS KARAKTERDEÐERÝ FROM CUSTOMERS

SELECT ROUND(121.829,2) ---- 2 saða gider 5 den büyükse  bir yukarý yuvarlar 
SELECT ROUND(121.829,0) 
select 500%5----den kalaný bulur


ALTER TABLE CUSTOMERS
ADD PUAN FLOAT NULL;  -----KOLON EKLEME


UPDATE CUSTOMERS 
SET boþkolon = 'Ahmet'
select * from CUSTOMERS
update CUSTOMERS
set boþkolon = null

select * from CUSTOMERS

UPDATE CUSTOMERS
SET boþkolon= ISNULL(boþkolon,2) 

SELECT * FROM CUSTOMERS


SELECT 
      CUSTOMERNAME,
	  boþkolon,CASE
	  WHEN CITYID>60 THEN '60'
	  WHEN CITYID BETWEEN 60 AND 40 THEN '70'
	  ELSE '80'
	  END AS PUAN
	  FROM CUSTOMERS

UPDATE CUSTOMERS
SET boþkolon = 
case 
when CITYID>50 THEN 20
when CITYID BETWEEN 50 AND 81 THEN 10
ELSE 5
END;

SELECT * FROM CUSTOMERS


UPDATE CUSTOMERS
SET boþkolon =  
case
when cýtyýd>50 then 20
when cýtyýd between 50 and  45 then 30
else 40
end;


select * from CUSTOMERS

SELECT CUSTOMERNAME,MAX(DISTRICTID) AS TUTARLAR FROM CUSTOMERS

SELECT CUSTOMERNAME,MAX(DISTRICTID) AS TUTARLAR FROM CUSTOMERS----GROUP BY ÝLE CUTOMERNAME SÜTUNUNU TANIMLADIK 
GROUP BY CUSTOMERNAME

SELECT CUSTOMERNAME,TCNUMBER,MAX(DISTRICTID) AS TUTARLAR FROM CUSTOMERS  ---BURDA GROUP BY  ÝLE TANIMLADIKTAN SONRA SIRALADIK 
GROUP BY CUSTOMERNAME,TCNUMBER ORDER BY MAX(DISTRICTID) DESC     
SELECT AVG(CITYID) FROM CUSTOMERS --AVG ORTALAMA HESABI YAPAR SÜTUN ÝÇÝN 
SELECT COUNT(*) AS ADETSAYISI,DISTRICTID FROM CUSTOMERS ---DISTRICTID NUMARASI 2 OLAN 3 KÝÞÝ VARMIÞ  BUNLARI KÜÇÜKTEN BÜYÜÐE DOÐRU SIRALATIK ADETLERÝNE GÖRE
GROUP BY  DISTRICTID
ORDER BY DISTRICTID

SELECT COUNT(*) AS ADETSAYISI,DISTRICTID FROM CUSTOMERS ---DISTRICTID NUMARASI 2 OLAN 3 KÝÞÝ VARMIÞ  BUNLARI KÜÇÜKTEN BÜYÜÐE DOÐRU SIRALATIK ADETLERÝNE GÖRE
GROUP BY  DISTRICTID
ORDER BY DISTRICTID

select * from CUSTOMERS WHERE CITYID IS NULL
SELECT COUNT(*) AS BOÞDEÐERSAYISI FROM CUSTOMERS WHERE CITYID IS NULL
SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID>60