SELECT * FROM CUSTOMERS 
WHERE CUSTOMERNAME LIKE 'A%'

--- LIKE 
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE  'A%' AND GENDER LIKE 'E' 
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE  'A%' OR  GENDER LIKE 'E'  --or  ya da demek and ve demek lýke harf ile baþlayan  iile içinde ara demek

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE>='1990.01.01'
AND BIRTHDATE<='1995.12.31'                       ---between  arasýna demek                            

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN 
'1990.01.01' AND '1995.12.31' 
 
select * from CUSTOMERS
where  YEAR(BIRTHDATE) BETWEEN 1990 AND 1995

SELECT C. *,CT.CITY FROM CUSTOMERS C              -----INNER JOIN ÝLE CITIES TABLOSUNU ÇAÐIRIYORUZ   ALYAS VERÝYORUZ  ON  YAPIYORUZ VE  CITY ID DE JOINLIYORUZ
INNER JOIN CITIES CT ON C.CITYID=CT.ID
WHERE CT.CITY='ÝSTANBUL'

select c. * ,ct.cýty from CUSTOMERS c
INNER JOIN CITIES ct on c.CITYID=ct.ID
where ct.CITY='ÝSTANBUL'
---SUBQUERUY
select (select CITY FROM CITIES WHERE ID =C.CITYID),  ---------------Subquery kullanarak joýnlemenen sorgu çekme iþlemi
* from CUSTOMERS C

WHERE
(SELECT CITY FROM CITIES WHERE ID =C.CITYID)='ÝSTANBUL'

----INNER JOIN 
SELECT CT.CITY,COUNT(C.ID) AS CUTOMERCOUNT FROM  CUSTOMERS C -----------ýnner joýn ve count kullanarak müþteri sayýsý 
INNER JOIN CITIES CT ON C.CITYID=CT.ID
GROUP BY CT.CITY
----AS ALYAS
select * from CUSTOMERS
select * from CUSTOMERS
select CUSTOMERNAME,TCNUMBER,ID from CUSTOMERS
SELECT CUSTOMERNAME,DISTRICTID,DISTRICTID+10000 as zamlýmaaþ,DISTRICTID-3000 as zamsýzmaaþ,DISTRICTID*2,DISTRICTID/2 FROM CUSTOMERS
select ct.CITY AS ÞEHÝR ,c.CUSTOMERNAME AS "MÜÞTER ÝSMÝ", c.ID AS MÜÞTERÝNO FROM  CUSTOMERS c ---- ALYAS VE  INNER JOIN  yeni sütun isimi arasýnda boþluk koymak isyiyorsam týrnak içine almamýz lazým
INNER JOIN CITIES ct ON c.CITYID=ct.ID
----DISTINCT
select distinct AGEGROUP FROM CUSTOMERS      ----ÇOÐUL SÜTÜNLARI TEKÝLLEÞTÝRÝRÝ DÝSTÝNCT ÝLE SAÐINDAKÝ KOLONUN TAMAMINA BAKARAK TEKÝL HALE GETÝRÝR   AYNI KAYIT OLMAZ 3 DEÐÝÞKENÝM OLSAYDI BU DAHA ZOR BÝR ÝHTÝMALDÝ
select distinct CUSTOMERNAME,AGEGROUP  FROM CUSTOMERS
select distinct AGEGROUP,CUSTOMERNAME FROM CUSTOMERS

----WHERE(GÖSTER)
SELECT * FROM  CUSTOMERS WHERE CITYID>50 AND CITYID<90  ------ þehir ýd si 50 ve 90  arasýnda  olanlarý  gösterir
SELECT* FROM CUSTOMERS WHERE CITYID>=50 OR CITYID<=30  ------ þehir ýd si 50 ve eliden büyük olnlar veya 30 ve 30 dan  küçük olanlarý gösterir
SELECT*FROM CUSTOMERS WHERE CITYID>50 ------------þehir ýd si 50 den büyük olnalarý gösterir
SELECT * FROM CUSTOMERS WHERE GENDER='K'----ERKEKLERÝ GÖSTER
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME ='Sevda AKÇAN'-- Sevda AKÇAN isimli þahýsý göster
SELECT * FROM CUSTOMERS WHERE TCNUMBER=42074151323-----420... li tc ye sahip kiþiyi göster 
--BETWEEN
SELECT * FROM CUSTOMERS WHERE CITYID BETWEEN 50 AND 90 ---------þehir ýd si 50 ve 90 arasýndakileri  gösterir 50 ve  90m da dahildir 
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME BETWEEN 'A' and 'c'---A=10 Z=99 c=100 büyüklük deðerleri küçük c Z den büyük olduðundan hepsini kapsar
---in (ÝÇÝNDE)
select distinct CUSTOMERNAME,CITYID From CUSTOMERS WHERE CITYID in(35,55,38)-----in ÝÇÝNDE not in ÝÇÝNDE OLMAYAN 
SELECT * FROM CUSTOMERS WHERE CITYID not in (55,35,65)
select * from CUSTOMERS where CUSTOMERNAME in('Sevda AKÇAN','Irmak HAMÝDÝ','Tuðçe AKKOÇ')--- ismi tam olarak yazarsak isediðimiz isimi bulduarabiliriz 
---LIKE(ÝSÝM HARF KELÝME ARAMA)
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'A%' ----A ile  baþlayan  isimler 
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE '%A'   ----A  ile  biten  isimler
SELECT CUSTOMERNAME FROM CUSTOMERS   
SELECT * FROM CUSTOMERS  WHERE CUSTOMERNAME LIKE 'Sevda%'----- Sevda ismindekileri göster.
SELECT * FROM CUSTOMERS  WHERE CUSTOMERNAME LIKE 'Sevda AKÇAN'---- Sevda AKÇAN ismini direkt gösterir
SELECT * from  CUSTOMERS where CUSTOMERNAME LIKE '%et'--------- et ile bitenleri  gösterir

----AND(VE)
----OR(VEYA)
SELECT * FROM CUSTOMERS WHERE GENDER='K' AND CUSTOMERNAME LIKE '%S%' AND CITYID>50 AND AGEGROUP='65 YAÞ ÜSTÜ' AND DISTRICTID=54 --- AND Ý BÝRDEN FAZLA KEZ  KULLANABÝLÝRÝZ
SELECT * FROM CUSTOMERS WHERE GENDER='K' OR (ID>200 AND CITYID=22)
SELECT DISTINCT AGEGROUP,CITY FROM CUSTOMERS C
INNER JOIN CITIES CT on C.CITYID=CT.ID
SELECT * FROM CUSTOMERS WHERE ID in (10,12,15)
SELECT * FROM CUSTOMERS WHERE ID=10 AND ID=12 AND ID=15
SELECT * FROM CUSTOMERS WHERE ID=10 OR ID=12 OR ID=15
SELECT * FROM CUSTOMERS WHERE GENDER='K' OR CITYID>50 AND DISTRICTID>200   ----Burda sadece  parantezleri  ya da ya alýr parantez dýþýnda kalan ve yi almaz  böylelikle iþlem karmaþýklýðý yaþanmaz
SELECT * FROM CUSTOMERS WHERE (GENDER='K' OR CITYID>50) AND DISTRICTID>200
select * from CUSTOMERS C
inner join CITIES CT ON CT.ID=C.CITYID WHERE C.ID in(22,21,30,73,40) AND CT.CITY LIKE 'K%'


-----ORDER BY (SIRALAMA)---ORDER BY EN SON YAZILIR
---ASC(1..9,A...Z)---ORDER BY  DAN SONRA BÝRÞEY YAZMSAAK ASC TÜRÜ SIRALAMA YAPAR
---DESC(100...1,z....A)

SELECT * FROM CUSTOMERS order by DISTRICTID
SELECT * FROM CUSTOMERS order by DISTRICTID ASC
SELECT * FROM CUSTOMERS order by DISTRICTID DESC 
SELECT * FROM CUSTOMERS ORDER BY  DISTRICTID,CITYID DESC   --- AND YAZMAMIZA GEREK YOK
SELECT * FROM CUSTOMERS ORDER BY  DISTRICTID,CITYID DESC
select * from CUSTOMERS order by 3 desc,6 asc-----3 . kolonu büyükten  küçüðüe doðru ve 6.kolonu küçükten büyüðe doðru sýralar
select * from CUSTOMERS order by 1 desc,7,8 desc



---UPPER YAZMIÞ OLDUÐUMUZ VERÝLERÝN TAMAMINI BÜYÜK HARFE ÇEVÝRÝR
---LOWER VERÝLERÝ KÜÇÜK HARFE ÇEVÝRÝR
---iNÝTCAP ÝLK HARFÝ BÜYÜK ANLAMINA GELÝR 
SELECT * FROM  CUSTOMERS
SELECT CUSTOMERNAME,upper(CUSTOMERNAME),AGEGROUP,lower(AGEGROUP) FROM CUSTOMERS
SELECT UPPER(CUSTOMERNAME) AS ÝSÝMSOYÝSÝM ,LOWER(AGEGROUP) AS YAÞGRUBU FROM CUSTOMERS
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME='SEVDA AKÇAN'
SELECT * FROM CUSTOMERS where upper(CUSTOMERNAME)='SEVDA AKÇAN'
SELECT * FROM CUSTOMERS WHERE LOWER(CUSTOMERNAME)='sevda akçan'


SELECT * FROM CUSTOMERS

----CONCAT(+)(Birleþtirme)(FROMDAN ÖNCE YAZILIR)(CONCAT FONKSÝYONU SADECE  ÝKÝ KARAKTER ALIR)( || BU ÝFADE 2 DEN FAZLA BÝRLEÞTÝRMEDE KULLANILIR)
SELECT CONCAT(CUSTOMERNAME,TCNUMBER) FROM CUSTOMERS
SELECT CUSTOMERNAME,TCNUMBER,CONCAT(CUSTOMERNAME|| ' ' || TCNUMBER) FROM CUSTOMERS --(HATALI ÇÜNKÜ 3 KARAKTER OLDU)
SELECT CUSTOMERNAME + ' ' + GENDER FROM CUSTOMERS----(||(ORACLE ÝÇÝN) MSSQL DE || YERÝNE + KULLANARAK BU ÝÞÝ YAPIYORUZ.BU ÝÞLEM ÝLE ÝSTEDÝÐÝMÝZ KADAR DEÐÝÞKEN  BÝRLEÞTÝREBÝLÝRÝZ VOÞLUK ÝÇÝN TIRNBAK ÝÇÝNE BOÞLUK ATMAMIZ GEREKLÝ)
SELECT CUSTOMERNAME + ' ' + GENDER +  ' ' + TCNUMBER FROM CUSTOMERS---ÝSTEDÝÐÝM KADAR UZATABÝLÝRÝM


-----SUBSTRING(KELÝME  TARAMA FONKSÝYONU)
SELECT * FROM CUSTOMERS
SELECT SUBSTRING(CUSTOMERNAME,1,3) FROM CUSTOMERS ----(ORACLE DA  SUBSTR MSSQL DE ÝSE SUBSTRING
SELECT SUBSTRING(CUSTOMERNAME,1,10) FROM CUSTOMERS-----(isimlerin birinci harfinden baþlayarak 10. harfine kadar tarar ve gösterir)
SELECT SUBSTRING(CUSTOMERNAME,0,10) FROM CUSTOMERS----(Baþlagýç olarak 1 ve 0 aynýdýr)
SELECT SUBSTRING(CUSTOMERNAME,1) FROM CUSTOMERS ----(bitiþ noktasýný yazmadýðuýmýzdan dolayý kod  dönmüyor)
SELECT SUBSTRING(CUSTOMERNAME,-3,6) FROM CUSTOMERS--(AYNI)
SELECT SUBSTRING(CUSTOMERNAME,1,2) FROM CUSTOMERS---(AYNI)

SELECT * FROM CUSTOMERS


---LEN(UZUNLUK ALIR)
SELECT LEN(CUSTOMERNAME) FROM CUSTOMERS----(ORACLE DA LENGTH OLARAK  KULLANILAN LEN OLARAK MSSQL DE KULLANILIR)
SELECT LEN(TCNUMBER) FROM CUSTOMERS 
SELECT CUSTOMERNAME,TCNUMBER,LEN(TCNUMBER) AS GEÇERSÝZ FROM CUSTOMERS WHERE LEN(TCNUMBER)<11----BUDA TC KÝMLÝK NUMARASI 11 DEN  KÜÇÜK OLAN KÝÞÝLERÝ GÖRDÜK
SELECT CUSTOMERNAME,CITYID,LEN(CITYID) AS GEÇERSÝZ FROM CUSTOMERS WHERE LEN(CITYID)>81---BURDA MAX 81 OLACAÐI ÝÇÝN 81 DEN BÜYÜKLERÝ GÖSTER DEEDÝK



---CHARINDEX&INSTR(ARADIÐIMIZ HARFÝ VEYA ÖBEÐÝN KAÇINI SIRADA OLDUÐUNU SÖYLEYEN BÝR FONKSÝYON)(ORACLEDA INSTR KULLANILIR)
SELECT CHARINDEX('A',CUSTOMERNAME) FROM CUSTOMERS---- A harfiinin satýrdaki  iþsim tütununda kaçýncý harf olduðunu söyler
SELECT CHARINDEX('B',CUSTOMERNAME) FROM CUSTOMERS

SELECT * FROM CUSTOMERS
--RIGHT(SAÐA KAYDIR) VE LEFT(SOLA KAYDIR) ORACLESQL ÝÇÝN =LPAD(SOLA DAYALI),RPAD(SAÐA DAYALI)
SELECT RIGHT(CUSTOMERNAME,5) FROM CUSTOMERS---- SAÐDAN ÝLK 5 KARAKTERÝ GÖSTERÝR
SELECT LEFT(CUSTOMERNAME,5) FROM CUSTOMERS----- SOLDAN  ÝLK 5 KARAKTERÝ GÖSTERÝR


---REPLACE(HÜCREDEKÝ KELÝMLERÝN HARFLERÝNÝ DEÐÝÞTÝRMEMÝZÝ SAÐLAR)
SELECT REPLACE(CUSTOMERNAME,'A','w') FROM CUSTOMERS---(CUSTOMERNMAE SÜTUNUNDAKÝ A HARFLAEREÝNÝ W YAP)
SELECT REPLACE(EMAIL,'S','E') FROM CUSTOMERS---EMAILDEKÝ S HARFLERÝNÝ  E YAP)
SELECT * FROM CUSTOMERS


----TRIM(HARF ÝLE KELÝMEDEKÝ ÝLK HARFÝ VE SON HARFÝ SÝLER VE GÖSTERÝR)

--Tarih Fonksiyonlarý

--DÖNÜÞÜM FONKSÝYONLARI 
select * from CUSTOMERS
select to_char(BIRTHDATE) FROM CUSTOMERS----to_char oracle sql de kullanlýr mssqlde kullanýlmaz bunun yerine FORMAT  ibaresi kullanýlýr


SELECT FORMAT(BIRTHDATE, '2024-12-04') AS FormattedBirthdate 
FROM CUSTOMERS;

SELECT CONVERT(VARCHAR, BIRTHDATE, 103) AS FormattedBirthdate 
FROM CUSTOMERS;

SELECT CAST('123456' AS INT) AS SayisalDeger;   ----CAST ÝLE KARAKTER BÝR ÝFADEYÝ SAYISAL BÝR DEÐERE DÖNÜÞTÜRME
SELECT TRY_CAST('abc' AS INT) AS SayisalDeger;  -- NULL döner, hata vermez.
SELECT TRY_CONVERT(INT, '123.45') AS SayisalDeger; -- NULL döner, hata vermez.
-- CAST Kullanýmý
SELECT CAST(123 AS VARCHAR) AS KarakterDeger;----------SAYISAL BÝR ÝFADEYÝ KARAKTERE DÖNÜÞTÜRME
-- CONVERT Kullanýmý
SELECT CONVERT(VARCHAR, 123) AS KarakterDeger;


-- Karakter kolonunu sayýsal kolona dönüþtürme        ----ÝKÝ DÖNÜÞÜMÜDE CAST FONKSÝYONU ÝLE GERÇEKLEÞTÝREBÝLÝRÝZ
SELECT CAST(TCNUMBER AS FLOAT) AS SayisalDeger
FROM CUSTOMERS;

-- Sayýsal kolonunu karakter kolonuna dönüþtürme
SELECT CAST(CUSTOMERNAME AS VARCHAR) AS KarakterDeger
FROM CUSTOMERS;
-- Karakter Kolonunu Tarih Formatýna Dönüþtürme      ------iKÝ DÖNÜÞÜMÜ DE CAST FONKSÝYONU KULLANARAK GERÇEKLEÞTÝREBÝLÝRÝZ
SELECT CAST(BIRTHDATE AS DATE) AS TarihDegeri
FROM CUSTOMERS;

-- Tarih Kolonunu Karakter Formatýna Dönüþtürme
SELECT CONVERT(VARCHAR, BIRTHDATE, 104) AS KarakterDegeri
FROM CUSTOMERS;                                             
--101	MM/dd/yyyy	12/04/2024
--103	dd/MM/yyyy	04/12/2024    
--104	dd.MM.yyyy	04.12.2024
--120	yyyy-MM-dd HH:mm:ss	2024-12-04 00:00:00

--Sayýsal Fonksyonlar 
select round(48.829,2)--virgülün saðýndaki kadar ilerler ve sðýndaki  rakam 5 den büyükse bir  yukarý  5 den küçükse bir aþaðý yuvarlar
select round(43.81,1)
select round(678.4567,3)
select round(678.4567,0)---o olunca  ondalýk kýsmý atýyor
select round(643.567,-3)


select round(347.789,2,1)--yuvarlamadan kesmek için 1 kullanýyoruz bu yüzden 2 saða gelip  kesiyor
select round(12345.78523,3,2) ----2 nin burda bir iþlevi yok sadece kesme nalamýna geliyor
select 100 % 3 ---kalan deðeri verir 100 e böyler 3 ü
select 500%5
select 600%4
select 145%8
select 1111%9

select * from CUSTOMERS
------GENEL FONKSÝYONLAR
ALTER TABLE CUSTOMERS
ADD boþkolon NVARCHAR(MAX) NULL;  -----burdaa alder table komutu ile add ile ekle  deyip boþkolon isimin bir  nvarchar(max) null olan bir boþ sütun ekledik
SELECT * FROM CUSTOMERS
SELECT boþkolon,ISNULL(boþkolon,'A') as doldurulmuþkolon FROM CUSTOMERS----SÜTUNDAKÝ BOÞ VERÝLERÝ ÝSTEDÝÐÝMÝZ ÞEKÝLDE  DOLDURUR
SELECT ISNULL(boþkolon,'MAMÝ') FROM CUSTOMERS
SELECT ISNULL(boþkolon,'1903') FROM CUSTOMERS
SELECT * FROM CUSTOMERS
UPDATE CUSTOMERS -----CUSTOMER TABLOSUNDA  boþkolon sütununa customers tablosunda  ýd  sütununda 1  olan veri için deðer1 yazdýrýr
SET boþkolon ='Deðer1'
WHERE ID = 1 
UPDATE CUSTOMERS-----Cutsomers tablosunda  boþkolon sütununa NULL kelimesini yazzdýrýr!
SET boþkolon = 'NULL'
UPDATE CUSTOMERS-------Cutsomers tablosunda boþkolon sütunundaki verilerin hespisini temizler sütunu boþaltýr (null) durumu gerçekleþir
SET boþkolon = NULL
SELECT * FROM CUSTOMERS
SELECT boþkolon,ISNULL(boþkolon,'2') as doldurulmuþkolon from CUSTOMERS

SELECT * fROM CUSTOMERS

--case expresion ( koþullu  ifadler) (oracle sql için )
--select case when .... then ....
           ----when .....then ...
			---else ....
			---end from tablo adý 
--MS SQL DE  CASE  ÝLE SQL DE  SORGU KULLANIMI 
SELECT * FROM CUSTOMERS
SELECT  
      CUSTOMERNAME,
	  DISTRICTID, CASE 
	              WHEN DISTRICTID>250 THEN 'YÜKSEK'
				  WHEN DISTRICTID BETWEEN 50 AND 250 THEN 'ORTA'
				  ELSE 'DÜÞÜK'
				  END AS DISTRICTIDCategory
				  from CUSTOMERS
SELECT  CUSTOMERNAME,
        CITYID,
		CASE 
		WHEN CITYID>65 THEN 'YÜKSEK'
		WHEN CITYID BETWEEN 35 AND  65 THEN 'ORTA'
		ELSE 'DÜÞÜK'
		END AS CITYIDCategory
		FROM CUSTOMERS
--UPDATE SORGUSUNDA CASE  KULLANIMI 

UPDATE CUSTOMERS
SET boþkolon =
 case 
 when CITYID>50 THEN 20
 when cýtyýd between 50 and 81 then 10
 else 5
 end;

 SELECT * FROM CUSTOMERS
 SELECT CITYID,CUSTOMERNAME FROM CUSTOMERS WHERE CITYID>50
 SELECT 
       CUSTOMERNAME,
	   CITYID,
	   CASE
	   WHEN CITYID>50 THEN 'ALINIR'
	   ELSE 'ALINMAZ'
	   END AS CITYCategory 
	   FROM CUSTOMERS
 SELECT 
       CUSTOMERNAME,
	   CITYID,
	   CASE
       WHEN CITYID >50 THEN CITYID-15
	   WHEN CITYID BETWEEN 50 AND 70 THEN CITYID-20
	   ELSE CITYID-5
	   END AS CÝTYIDGÜNCEL
	   FROM CUSTOMERS

 ---BOÞ (NULL) DEÐER VAR MI ONU KONTROL ETME 
 SELECT* FROM  CUSTOMERS WHERE DISTRICTID IS NULL
 SELECT COUNT (*) AS BOÞDEÐERSAYISI FROM CUSTOMERS WHERE DISTRICTID IS NULL 
 

 
 SELECT * FROM CUSTOMERS
 SELECT
       CUSTOMERNAME,
	   GENDER,
	   CITYID,
	   CASE
	   WHEN CITYID=5 and gender='K'  THEN 'DÜÞÜKKADIN'
	   WHEN CITYID BETWEEN 5 AND 20 AND GENDER='K' THEN 'ORTAKADIN'
	   ELSE 'DÜÞÜKKADIN'
	   END AS KADINCATEGORY
	   FROM CUSTOMERS
SELECT * FROM CUSTOMERS
----GRUPLAMA FONKSÝYONLARI ÖNEMLÝ
SELECT AVG(CITYID) FROM CUSTOMERS --AVG ORTALAMA HESABI YAPAR SÜTUN ÝÇÝN 
SELECT AVG(DISTRICTID) FROM CUSTOMERS
SELECT COUNT(*) FROM CUSTOMERS WHERE CITYID>5-- 5 DEN BÜYÜK CITYID OLANLAR KAÇ KÝÞÝ  VARDIR COUNT SAYAR  
SELECT COUNT(*) FROM CUSTOMERS ---- TOPLAM DATA SAYISI GÖSTERÝR
SELECT COUNT(*) FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'A%'---ÝSMÝ A ÝLE BAÞLAYAN 78 KÝÞÝ  VARMIÞ 
SELECT COUNT(*) FROM CUSTOMERS WHERE CUSTOMERNAME LIKE 'A%' AND CITYID>5--ÇALIÞANLARDAN ÝSMÝ A ÝLE BAÞAYIP CÝTY ID SÝ 5  DEN FAZLA OLAN KAÇ KÝÞÝ  VAR 
SELECT MAX(DISTRICTID) FROM CUSTOMERS ----- MAXÝMUM DISTRICTID DEÐERÝ KAÇTIR
SELECT MIN(DISTRICTID) FROM CUSTOMERS------ MÝNUMUM DISTRICTID DEÐERÝ KAÇTIR
SELECT SUM(DISTRICTID) FROM CUSTOMERS-------ÇALIÞANLARIN TOPLAM DISTRICTID DEÐERLERÝ KAÇTIR SORUSUNU  CEVAPLAR 
SELECT AVG(DISTRICTID)AS ORT ,COUNT(*)AS KÝÞÝSAYISI,SUM(DISTRICTID)AS TOPLAM,MAX(DISTRICTID) AS MAX ,MIN(DISTRICTID) AS MÝN FROM CUSTOMERS
--SELECT * FROM CUSTOMERS WHERE ---SIRALAMA
--GROUP BY  
--ORDER BY 
------BU DONKSÝYONLARI GROUP BY ÝLE  SÜTUN BAZINDA TANIMLAMA
SELECT CUSTOMERNAME,MAX(DISTRICTID) AS TUTARLAR FROM CUSTOMERS ---GROUP BY ÝLE GRUPLAMADIÐIMIZDAN  DOLAYI GELMEDÝ

SELECT CUSTOMERNAME,MAX(DISTRICTID) AS TUTARLAR FROM CUSTOMERS----GROUP BY ÝLE CUTOMERNAME SÜTUNUNU TANIMLADIK 
GROUP BY CUSTOMERNAME

SELECT CUSTOMERNAME,TCNUMBER,MAX(DISTRICTID) AS TUTARLAR FROM CUSTOMERS  ---BURDA GROUP BY  ÝLE TANIMLADIKTAN SONRA SIRALADIK 
GROUP BY CUSTOMERNAME,TCNUMBER ORDER BY MAX(DISTRICTID) DESC     

SELECT COUNT(*) AS ADETSAYISI,DISTRICTID FROM CUSTOMERS ---DISTRICTID NUMARASI 2 OLAN 3 KÝÞÝ VARMIÞ  BUNLARI KÜÇÜKTEN BÜYÜÐE DOÐRU SIRALATIK ADETLERÝNE GÖRE
GROUP BY  DISTRICTID
ORDER BY DISTRICTID

SELECT AVG(DISTRICTID),CITYID FROM CUSTOMERS------CITYID SÝ 5 VEYA 20 OLANLARIN DISTRICTID DEÐERLERÝ ORTALAMASININ BÜYÜKTEN KÜÇÜÐE DOÐRU  SIRALA
WHERE CITYID=5 OR CITYID=20
GROUP BY CITYID
ORDER BY AVG(DISTRICTID)DESC


SELECT MAX(SUM(DISTRICTID) FROM CUSTOMERS-----HER ID ÝÇÝN TOPLAM DISTRIC DEÐERÝNÝ VERÝR VE BU DEÐERLERDEN EN BÜYÜÐÜNÜ ALIR
GROUP BY  CTIYID
  

----KURAL:GRUPLAMA FONKSÝYONLARI HÝÇBÝR ZAMAN ÝÇ ÝÇE 3 KEZ KULLANILAMAZ 

---GRUPLAMA FONKSÝYONLARINDA HAVÝNG KULLANIMI

SELECT  AVG(DISTRICTID) FROM CUSTOMERS WHERE AVG(DISTRICTID)>5000

SELECT boþkolon,AVG(DISTRICTID) FROM CUSTOMERS----BURDA YAPMAK ÝSTEDÝÐÝMÝZ ÞEY BOÞKOLON ID LERÝNE GÖRE HRT BÝR ID NIN DISRCTIT ORTALAMALRINI HESAPLAYIP BUNLARDAN DA SAECE
WHERE AVG(DISTRICTID)>430                          ---430 DAN BÜYÜKLERÝ GÖSTERMEK FAKAT HATALIU BÝR ÝÞLEM BUNU ALTTTA HAVING FONKSÝYONUYLA HALLEDELÝM
GROUP BY  DISTRICTID

--HAVÝNG
--SELECT * FROM TABLO ADI    ------ SIRALAMA BURDUR MS SQL DE BU YAPI ÇOK ÖNEMLÝ BUNUN ÜSTÜNE ÇIKMAZ KOD OLARAK 
--WHERE
--GROUP BY 
--HAVING
--ORDER BY 

SELECT boþkolon,AVG(DISTRICTID) FROM CUSTOMERS  ---ÝÞLEMÝ HAVING FONKSÝYONUYLA GERÇEKLEÞTÝRDÝK VE BÜYÜKTEN KÜÇÜÐE DOÐRU SIRALADIK
GROUP BY boþkolon                               --AYNI ID DE  OLANLARIN ORTALAMASINI ALIYOR 430 DAN BÜYÜK OLANLARI BÜYÜKTEN KÜÇÜÐE DOÐRU SIRALIYOR
HAVING AVG(DISTRICTID) >430
ORDER BY AVG(DISTRICTID)DESC


SELECT boþkolon,MAX(DISTRICTID) FROM CUSTOMERS---AYNI ID DE OLANLARIN DISTRIDTID DEÐERLERÝNDEN HER BÝR  ID ÝÇÝN EN BÜYÜÐÜ SEÇÝYOR BU SEÇLÝLEN DEÐERLERDEN DE 650 DEN BÜYÜK OLAN
GROUP BY boþkolon                             ---OLANLARI BÜYÜKTEN  KÜÇÜÐE DOÐRU SIRALIYOR
HAVING MAX(DISTRICTID)>650
ORDER BY  MAX(DISTRICTID) DESC 


SELECT boþkolon,COUNT(DISTRICTID) AS dýstýrýnctsayýsý FROM CUSTOMERS---BOÞKOLONDAKÝ 20 VE 40 KATEGORÝLERÝNDE HER BÝR KATEGORÝ ÝÇÝN DISTIRICTID SAYISI65 DEN BÜYÜKLERÝ   BGÜYÜKTEN BÜÇÜÐE DOÐRU SIRALA 
GROUP BY boþkolon                          
HAVING COUNT(DISTRICTID)>65
ORDER BY  COUNT(DISTRICTID) DESC 

SELECT * FROM CUSTOMERS
SELECT boþkolon,MIN(DISTRICTID) FROM CUSTOMERS
GROUP BY  boþkolon
HAVING MIN(DISTRICTID)<50
ORDER BY MIN(DISTRICTID) ASC


select AGEGROUP,COUNT(DISTRICTID) FROM CUSTOMERS
GROUP BY AGEGROUP
HAVING COUNT(DISTRICTID)<60
ORDER BY COUNT(DISTRICTID) DESC


--Subqery SytnaX

 SELECT * FROM CUSTOMERS

 SELECT * FROM CUSTOMERS WHERE DISTRICTID > (SELECT DISTRICTID FROM CUSTOMERS WHERE CITYID=180)  -- CITY ID SÝ 180 NOLANLARIN  DISTIRINCTID SÝNDDEN BÜYÜK OLAN DISTIRINCTID  LERÝ  GÖSTER
 SELECT * FROM CUSTOMERS WHERE DISTRICTID = (SELECT DISTRICTID,CUSTOMERNAME FROM CUSTOMERS WHERE CUSTOMERNAME='Sevda AKÇAN')---BURDA  SUBQUERY ÝÇÝNDEKÝ sorgu eðer bir satýrdan fazlaysa sorgunun tamamý hata verir
 SELECT * FROM CUSTOMERS C                       --- < > yerine in kullanabiliriz  böylelikle hata ordtadan kaklmýþ olur.
 INNER JOIN CITIES CA ON CA.ID=C.CITYID WHERE CITYID =(SELECT CITYID FROM CUSTOMERS WHERE CITYID=69)----TEK BÝR TAANE SÜTUN OLACAK KÝ GÖNSÜN
 SELECT * FROM CUSTOMERS C                       --- < > yerine in kullanabiliriz  böylelikle hata ordtadan kaklmýþ olur.
 INNER JOIN CITIES CA ON CA.ID=C.CITYID WHERE CITYID =(SELECT CUSTOMERNAME,CITYID FROM CUSTOMERS WHERE CITYID=69)--BURDA ÇALIÞMADI CUSTOMER NAMEDEN DOLAYI
 SELECT * FROM CUSTOMERS C                       --- < > yerine in kullanabiliriz  böylelikle hata ordtadan kaklmýþ olur.
 INNER JOIN CITIES CA ON CA.ID=C.CITYID WHERE CITYID IN (SELECT CUSTOMERNAME,CITYID FROM CUSTOMERS WHERE CITYID=69)---CUSTOMERNAME ZATEN BENDE VAR DÝYOR
 SELECT * FROM CUSTOMERS C
 INNER JOIN CITIES CT ON CT.ID=C.CITYID WHERE CITYID > (SELECT CITYID FROM CUSTOMERS WHERE CITYID=25)----BURDA ÇALIÞMADI ÇOK SATIR OLUÐU ÝÇÝN 
  SELECT * FROM CUSTOMERS C
 INNER JOIN CITIES CT ON CT.ID=C.CITYID WHERE CITYID > (SELECT CITYID FROM CUSTOMERS WHERE CITYID=69)   ---BÝR TAANE DÖNDÜÐÜ ÝÇÝN ÇALIÞTI
   SELECT * FROM CUSTOMERS C
 INNER JOIN CITIES CT ON CT.ID=C.CITYID WHERE CITYID > (SELECT CITYID FROM CUSTOMERS WHERE CITYID=25) ORDER BY CITYID DESC;---SIRLAMADI DÖNGÜ SATIRI ÇOK OLDUÐUNDAN 

 SELECT * 
FROM CUSTOMERS C
INNER JOIN CITIES CT ON CT.ID = C.CITYID 
WHERE DISTRICTID > (SELECT MAX(DISTRICTID) FROM CUSTOMERS WHERE CITYID = 25)-----CITY ID SÝ 25 OLAN VERÝLERDE DISTIRICTID ID SÝ EN BÜYÜK OLANDAN DAHA BÜYÜK DISTIRICT ID YE SAHÝP OLAN BÝREYLERÝ BÜYÜKTEN  KÜÇÜÐE DOÐRU SIRALA
ORDER BY CITYID DESC;

SELECT CUSTOMERNAME FROM CUSTOMERS WHERE CITYID >(SELECT CITYID FROM CUSTOMERS WHERE CITYID = 69)---YÝNE ÇALIÞTIRMADI TEK SATIR VE TEK SÜTUN OLUCAK
SELECT * FROM CUSTOMERS WHERE CITYID >(SELECT CITYID FROM CUSTOMERS WHERE CITYID = 69) ORDER BY CITYID DESC--ÇALIÞTI VE SIRALADI



-----SET OPERATÖELERÝ(ALT ALTA SIRALAMA) --BU OPERTÖRLERÝ KULLANMAK ÝÇÝN  ÝKÝ TABLONUNDA KOLON SAYILARI AYNI OLMASI GEREKÝYOR VEYA ÝSTENÝLEN KOLONLAR AYNI ÝSÝMDE OLMASI GEREKÝYOR
SELECT * FROM CUSTOMERS  ----ÇALIÞMAZ ÇÜNÜ ÝKÝ TABLONUN KOLON SAYILARI AYNI DEÐÝL 
union 
SELECT * FROM CITIES
-------------------------------
SELECT ID FROM CUSTOMERS --- ID ÜZERÝNDE ÇALIÞTI union:ÝKÝ KOLONDAKÝ VERÝLERÝ BÝRLEÞTÝRÝR AYNI OLANLARI ÝKÝ DEFA ALMAZ BRÝ DEFA ALIR
union 
SELECT ID FROM CITIES
SELECT ID FROM CUSTOMERS----- ID ÜZERÝNDE ÇALIÞTI:union all:ÝKÝ KOLONDAKÝ VERÝLERÝ BÝRLEÞTÝRÝR AYNI OLANLARI DA ÝKÝ DEFA ALIR(HER AYNI SAYIDAN BÝRER TAANE OLUR)
union all
SELECT ID FROM CITIES
SELECT ID FROM CUSTOMERS------ ID ÜZERÝNDE ÇALIÞTI:intersect:ÝKÝ KOLONDA DA SEDECE ORTAK OLAN VERÝLERÝ ALIR 
intersect
SELECT ID FROM CITIES
SELECT ID FROM CUSTOMERS------ID  ÜZERÝNDE ÇALIÞTI:CUSTOMERSDEKÝ ID LERÝ ALIR SADECE ORTAK OLAN IDLERÝ ALMAZ SADECE CUSTOMERS TABLOSUNA ÖZEL OLAN IDLERÝ ALIR
EXCEPT
SELECT ID FROM CITIES
SELECT ID FROM CITIES---------ID ÜZERÝNDEN CITIES E ÖZEL BÝR ID YOK YANÝ CITIESDEKÝ IDLERÝN HEPSÝ CUSTOMERS DE DE VAR 
EXCEPT
SELECT ID FROM CUSTOMERS
SELECT ID,CUSTOMERNAME FROM CUSTOMERS----
union 
SELECT ID,CITY FROM CITIES
SELECT ID,CITYID FROM CUSTOMERS----ÇALIÞMAZ KARIÞLIK GELEN VERÝ TÝPLERÝ AYNI OLMASI GEREKÝYOR CITYID ÝLE CITY AYNI TYPE SAHÝP DEÐÝL KOLON SAYILARI VE
union                          ----KOLON SAYILARI AYNI OLACAK VE DENK GELEN KOLONLARIN VERÝ TÝPÝ DE AYNI OLACAK
SELECT ID,CITY FROM CITIES-------ÇALIÞTI ÇÜNKÜ VERÝ TÝPLERÝ VE KLONLAR AYNI ID(NUMBER),CITY(VARCHAR)
union
SELECT CITYID,CUSTOMERNAME FROM CUSTOMERS

SELECT ID,CUSTOMERNAME,CITYID FROM CUSTOMERS---ÇALIÞMADI 
union
SELECT ID,'yok' FROM DISTRICTS

SELECT ID, CUSTOMERNAME, CITYID -------BURDA CITYID YERÝNE BOÞ BIRKATIK AYNI TÝP OLMASI  YETERLÝ VE KOLON SAYISI AYNI OLMASIYETERLE ÝTSEDÝÐÝMÝZ GÝBÝ  OYNAYABÝLÝRÝZ 
FROM CUSTOMERS                   ------ BÝR ÝSÝSM BÝR YOKM DÝYE GÝÞTMÝÞÝ VARCHAR VERÝ TÝPÝNDE TRINAKL ÝÇÝNDE ÝSTEDÝÐÝMÝZLE KULLANUABÝLÝRÝZ.
UNION
SELECT ID, 'yok' AS CUSTOMERNAME,0
FROM DISTRICTS;


SELECT ID, CUSTOMERNAME, CITYID -------BURDA CITYID YERÝNE NULL BIRKATIK AYNI TÝP OLMASI  YETERLÝ VE KOLON SAYISI AYNI OLMASIYETERLE ÝTSEDÝÐÝMÝZ GÝBÝ  OYNAYABÝLÝRÝZ 
FROM CUSTOMERS                   ------ BÝR ÝSÝSM BÝR YOKM DÝYE GÝÞTMÝÞÝ VARCHAR VERÝ TÝPÝNDE TRINAKL ÝÇÝNDE ÝSTEDÝÐÝMÝZLE KULLANUABÝLÝRÝZ.
UNION
SELECT ID, 'yok' AS CUSTOMERNAME,NULL
FROM DISTRICTS;

SELECT ID,'2023MÜÞTERÝID' AS MÜÞTERÝID FROM CUSTOMERS----MÜÞTERÝLERÝN DEVAMLILIKLARI BU TÝP AYARLAYABÝLÝRÝZ
UNION
SELECT ID,'2024MÜÞTERÝID' FROM CITIES
UNION
SELECT ID,'2025MÜÞTERÝID' FROM DISTRICTS



----TABLO OLUÞTURMA 
CREATE TABLE Personel (
  PersonelID INT IDENTITY(1,1) PRIMARY KEY,---Otomatik artan ve benzersiz deðerlerle dolurulmasýný saðlar 
  Ad NVARCHAR(50),---Maksimum 50 karakter alabilen Unicode destekli metin
  Soyad NVARCHAR(50),-----Maksimum 50 karakter alabilir
  Maas DECIMAL(10,2),----virgülden  önce  8 sonra 2 basamak deðer 
  DogumTarihi DATE,--- Tarih(yyy-mm-dd) formatýnda
  GirisTarihi DATETIME,----Tarih ve saat (yyyy-mm-dd hh:mm:ss)
  Aktif BIT --- 0 veya 1 (Boolean)
  );



  --INSERT(Kayýt ekleme)

  INSERT INTO Personel(Ad,Soyad,Maas,DogumTarihi,GirisTarihi,Aktif)
  VALUES
  ('Ali','Veli',4500.50,'1990-05-12','2024-12-30 08:00',1),
  ('Ayþe','Demir',5000.00,'1988-11-22','2023-03-15 09:00',1)
 
  INSERT INTO Personel(Ad,Soyad,Maas)
  VALUES
  ('Muhammed','Hanoðlu',4500,00),
  ('Aysu','Keklik',6000,20)

  --DELETE KAYIT SÝLME
  DELETE FROM Personel---Soyadý hanoðlu olan kaayýtlarý sil 
  WHERE Soyad='Hanoðlu'

---Tüm kayýtlarý sil
TRUNCATE TABLE Personel

---ALTER TABLE(KOLON  EKLEME)
ALTER TABLE Personel----doðum tarihi kolonunu girdi tarih olarak
ADD DoðumTarihi DATE

ALTER TABLE Personel
ADD
   MESLEK NVARCHAR(10),
   FORMA_NUMARASI DECIMAL(5);

----KOLON SÝLME
ALTER TABLE Personel
DROP COLUMN DoðumTarihi;


----VERÝ GÜNCELLEME
  UPDATE Personel --------Maaþý 4500.50 olan kiþilere  300 zam yap ve aktif durumunu kapat
  SET Maas = Maas +300,Aktif = 0
  WHERE Maas =4500.50

  UPDATE Personel---ismi muhammed  olan ve pasif olaanlara  900 zam yap ve aktife çevir 
  SET Maas = Maas+900,Aktif=1
  Where Ad='Muhammed' and Aktif=0


  --YENÝ TABLO OLUÞTURMA 
  SELECT * INTO YENÝTABLO--mevcut  tablodan yeni bir tablo oluþturur
  FROM Personel
  WHERE Maas > 5000


---BÝR TABLODAN  BAÞKA tabloya veri aktarma  veya gücelleme
MERGE INTO Personel as Hedef
USING YeniPersonel as  kaynak
ON hedef.PersonselID = kaynak.PersonelID
WHEN MATCHED THEN
  UPDATE SET Maas = kaynak.Maas
  When  not matched by target then
  INSERT (Ad,Soyad,Maas)
  VALUES (kaynak.ad,kaynak.soyad,kaynak.Maas);
  

  ------------------------------ÝÞ HAYATINDAKÝ KODLAR------



 -- Gruplama ve Toplama Ýþlemleri

SELECT Kategori, COUNT(*) AS Toplam, AVG(Fiyat) AS OrtalamaFiyat
FROM Urunler
GROUP BY Kategori
HAVING AVG(Fiyat) > 100;

---Kolon Adý Deðiþtirme

EXEC sp_rename 'TabloAdý.EskiKolonAdý', 'YeniKolonAdý', 'COLUMN';


--Performans Optimizasyonu
--Index Oluþturma
CREATE INDEX IX_Personel_Ad ON Personel (Ad)

--Index Silme
DROP INDEX IX_Personel_Ad ON Personel
--Query Planýný Ýnceleme

SET STATISTICS TIME ON;
SET STATISTICS IO ON;


--LEFT JOIN

SELECT Personel.Ad, Departman.DepartmanAdý
FROM Personel
LEFT JOIN Departman ON Personel.DepartmanID = Departman.DepartmanID;
--CROSS JOIN

SELECT * FROM Personel CROSS JOIN Departman;


--Geliþmiþ Ýþlemler
--CTE (Common Table Expression) Kullanýmý

WITH MaasCTE AS (
    SELECT Ad, Maas FROM Personel WHERE Maas > 5000
)
SELECT * FROM MaasCTE;
--Pivot Ýþlemi

SELECT *
FROM (
    SELECT Ay, SatisMiktari FROM Satis
) AS Kaynak
PIVOT (
    SUM(SatisMiktari) FOR Ay IN ([Ocak], [Þubat], [Mart])
) AS PivotTablo;
---Hata Yönetimi
---TRY...CATCH Bloðu

BEGIN TRY
    DELETE FROM Personel WHERE Maas < 0;
END TRY
BEGIN CATCH
    PRINT 'Hata Oluþtu: ' + ERROR_MESSAGE();
END CATCH;

